name: 'Generate Documentation'

on:
  push:
    branches: [master, homework4]
    paths:
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - 'Doxyfile'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [master]
  workflow_dispatch:  # 👈 Ручной запуск

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          destination_dir: .
          keep_files: false